version: 2
jobs:
  test:
    macos:
      xcode: "9.2.0"
    steps:
      - checkout
      - run:
          name: Run tests
          command: fastlane scan
          environment:
            SCAN_DEVICE: iPhone 8 Plus
            SCAN_SCHEME: DrinkOrSink
      - store_test_results:
          path: fastlane/test_output/report.xml
