version: 2
jobs:
  build-and-test:
    macos:
      xcode: "9.2.0"
    steps:
      - checkout
      - run:
        name: Install fastlane
        command: sudo gem install fastlane
      - run:
        name: Build and run tests
        command: fastlane scan
        environment:
          SCAN_DEVICE: iPhone 8 Plus
          SCAN_SCHEME: DrinkOrSink
      - store_test_results:
        path: test_output/report.xml
      - store_artifacts:
        path: /tmp/test-results
        destination: scan-test-results
      - store_artifacts:
        path: ~/Library/Logs/scan
        destination: scan-logs

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test
