version: 2
jobs:
  build-and-test:
    macos:
      xcode: "9.2.0"
    shell: /bin/bash --login -eo pipefail
    working_directory: /Users/distiller/project
    environment:
      FL_OUTPUT_DIR: /Users/distiller/project/output
    steps:
      - checkout
      - run: mkdir $FL_OUTPUT_DIR
      - run: gem install bundler
      - run: bundle install
      - run: bundle exec fastlane test
      - store_artifacts:
          path: /Users/distiller/project/output
      - store_test_results:
          path: /Users/distiller/project/output/scan

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test
